export const INDUCTRIES_JSON = [
  'Agriculture',
  'Apparel',
  'Banking',
  'Biotechnology',
  'Chemical',
  'Communications',
  'Construction',
  'Consulting',
  'Education',
  'Electronic',
  'Energy',
  'Engineering',
  'Entertainment',
  'Environmental',
  'Finance',
  'Food & Beverage',
  'Government',
  'Health care',
  'Hospitality',
  'Insurance',
  'Machinery',
  'Manufacturing',
  'Media',
  'Not for profit',
  'Other',
  'Recreation',
  'Retail',
  'Shipping',
  'Technology',
  'Telecommunications',
  'Transportation',
  'Utilities'
];

export const COMPANY_TYPE_JSON = [
'Distributor',
'Retailer',
'Flagship',
'Dealer',
'Service Center',
'Partner',
'Reseller',
'Prospect',
'Supplier',
'Investor',
'Direct Customer',
'Other'
];

export const COMPANY_OWNERSHIP_JSON = [
  'Public',
  'Private Limited',
  'Subsidiary',
  'Government',
  'Service Center',
  'Privately Held',
  'Partnership',
  'Other'
];
